services:
  todoapi:
    build:
      context: ./TodoApp
      dockerfile: Dockerfile
    ports:
      - "5080:5080"
    volumes:
      - ./Todo.db:/app/Todo.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
